### ISSUE TITLE
Receiving only message "TestBody" 

### ISSUE THREAD

**Issue by kim257** [kubemq-io/kubemq-node#4]
kubeMQ form : https://hub.docker.com/r/kubemq/kubemq/tags

`docker run -d -p 8080:8080 -p 50000:50000 -p 9090:9090 -v kubemq-vol:/store -e KUBEMQ_TOKEN=mytoken --name kubemq  kubemq/kubemq`

**Receiving Query Requests**
My code
<img width="671" alt="Screen Shot 2562-12-11 at 16 35 04" src="https://user-images.githubusercontent.com/16816483/70609355-374ea700-1c34-11ea-9e69-d2a3ca4012ac.png">

Result
<img width="503" alt="Screen Shot 2562-12-11 at 16 35 41" src="https://user-images.githubusercontent.com/16816483/70609427-59482980-1c34-11ea-9900-696b1b9f2809.png">

**Sending Query Requests**
my code
<img width="694" alt="Screen Shot 2562-12-11 at 16 37 59" src="https://user-images.githubusercontent.com/16816483/70609596-a6c49680-1c34-11ea-904b-68bdcbec7cee.png">

Result
<img width="492" alt="Screen Shot 2562-12-11 at 16 38 07" src="https://user-images.githubusercontent.com/16816483/70609615-afb56800-1c34-11ea-9b7e-b238972be178.png">

**Postman Send Query Request**
<img width="651" alt="Screen Shot 2562-12-11 at 16 40 24" src="https://user-images.githubusercontent.com/16816483/70609904-310cfa80-1c35-11ea-934e-90700729f51e.png">

Why i receive only message  **TestBody**

**Comment by eitam-ring** [comment]
Hey Kim,
Thanks for the query.
Since the version you are using we update the SDK a few times and fixed this issue
Please take a look at attach example based on the code you sent:

Receiver
![image](https://user-images.githubusercontent.com/45172109/72048862-a5c76900-32b5-11ea-8172-953cebe00bb8.png)

![image](https://user-images.githubusercontent.com/45172109/72048877-ae1fa400-32b5-11ea-9e4b-9d6b65e388d5.png)

Sender

![image](https://user-images.githubusercontent.com/45172109/72049082-25edce80-32b6-11ea-8b35-cbcb5ca8025c.png)

![image](https://user-images.githubusercontent.com/45172109/72049098-2be3af80-32b6-11ea-81b9-80625b8a661d.png)

Attached is the code:


[kimNodeTest.zip](https://github.com/kubemq-io/kubemq-node/files/4039281/kimNodeTest.zip)
